server:
  shutdown: graceful # Ensures graceful shutdown in containers/k8s
  servlet:
    context-path: /spring # Sets a global prefix between domain & all endpoints, {domain}/{prefix}/{endpoint}
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8080 #Server port config. Valid range: 0 → 65535 
  ssl: #SSL TLS, Trust store, Key store
    enabled: false
    enabled-protocols: TLSv1.2,TLSv1.3
    protocol: TLSv1.2
    ciphers: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    trust-store: file:./src/main/resources/security/truststore.p12 # Holds trusted public certificates
    trust-store-password: changeit
    trust-store-type: PKCS12
    key-store: file:./src/main/resources/security/keystore.p12 # Holds your own identity: your server's private key + certificate
    key-store-password: changeit
    key-store-type: PKCS12
    keyAlias: spring #Tell spring which key alias imported in PKCS12 file should use
    client-auth: want	#need: client must provide valid cert (strict), want: client cert is optional, none: no client validation (default)
  http2:
    enabled: true
spring:
  application:
    name: spring
  datasource: #DB Config(Git will auto build using the details config in repository secrets)
    url: jdbc:mysql://localhost:3306/appdb?createDatabaseIfNotExist=true
    username: root
    password: Pass@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30 # Defines how many connections can be open concurrently
      minimum-idle: 10 # Minimum idle connections in the pool(in count)
      idle-timeout: 600000  # Helps recycle connections and free up resources(in milliseconds). idle-timeout must be less than max-lifetime
      max-lifetime: 1800000  # Helps recycle connections and free up resources(in milliseconds). idle-timeout must be less than max-lifetime
      connection-timeout: 30000  # Maximum time to wait for a connection from the pool before throwing an exception(in milliseconds)
      leak-detection-threshold: 20000  # Helps identify if connections are not closed properly(in milliseconds)
      pool-name: HikariCP
      data-source-properties:
        # JDBC driver optimizations that reduce parsing overhead and improve latency
        cachePrepStmts: true  # Enable caching of prepared statements
        prepStmtCacheSize: 250 # Sets the number of prepared statements that the driver will cache per connection(in count)
        prepStmtCacheSqlLimit: 2048 # Sets the maximum length of SQL statements that will be cached
        useServerPrepStmts: true # Uses server-side prepared statements (MySQL feature); helps reduce client-side parsing
        useSSL: false
        requireSSL: false
        allowPublicKeyRetrieval: true
        # List of ssl mode:
        # DISABLED - SSL is not used
        # PREFERRED - SSL is used if available on the server
        # REQUIRED - SSL is required, but no certificate verification is done.
        # VERIFY_CA - SSL is required, and server cert must be signed by a trusted CA.
        # VERIFY_IDENTITY - Like VERIFY_CA, plus it validates hostname matches certificate CN/SAN.
        sslMode: DISABLED
        trustCertificateKeyStoreUrl: file:./src/main/resources/security/keystore.p12
        trustCertificateKeyStorePassword: changeit
        trustCertificateKeyStoreType: PKCS12
  jpa:
    open-in-view: false # Avoids lazy-loading leaks in enterprise apps
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      # none - No action. Hibernate will not touch the schema at all. Use this if you manage the schema manually
      # validate - Hibernate only validates that the schema matches the entity mappings. If something is missing (like a column or table), the app will fail to start. Useful for ensuring correctness without changing schema.
      # update - Hibernate will automatically update the schema to match entity mappings (create missing tables/columns, but not drop). Data is usually preserved, but this can be risky. Useful for dev, not for prod.
      # create - Hibernate will drop and recreate the schema at startup. All existing data is lost. Great for quick testing, but not safe otherwise.
      # create-drop - Same as create, but Hibernate will also drop the schema when the SessionFactory is closed (e.g., when the app shuts down). Useful for integration tests.
      ddl-auto: update
      naming: #To maintain the exact same table & column name defined in JPA class
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
  batch: #Batch job enablement config
    job:
      enabled: false
  task: #Schduler enablement config
    scheduling:
      enabled: true	
  mail:
    host: smtp.gmail.com
    port: 587
    username: test@gmail.com
    password: 123456
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    default-encoding: UTF-8
    sender: test@gmail.com
mybatis:
  mapper-locations: 
  - file:./src/main/resources/mybatis/mapper/*.xml # Location(s) of your MyBatis XML mapper files.
  type-aliases-package: com.modal # Package(s) to scan for domain/model classes to create type aliases automatically.
  configuration:
    # Automatically converts column names with underscores (snake_case) to camelCase in Java objects.
    # Example: database column "user_name" → Java property "userName".
    map-underscore-to-camel-case: true
    # Enables MyBatis first-level (per-session) and second-level (optional global) caching.
    # Can improve performance for repeated queries.
    cache-enabled: true
    # Sets the default fetch size for queries.  
    # This is a hint to JDBC driver on how many rows to fetch from DB at a time.
    default-fetch-size: 100
    # Sets the default statement timeout in seconds.  
    # If a query takes longer than this, it will throw a timeout exception.
    default-statement-timeout: 30
project:
  log:
    name: ./logs #dot refer to current path
rate:
  limit:
    defaultRate:
      capacity: 10 #max number of tokens the bucket can hold 
      tokens: 10 #new tokens add per period
      period: 60 #Timeunit, second
    endpoints:
      /v1/template/post:
        capacity: 10 #max number of tokens the bucket can hold 
        tokens: 10 #new tokens add per period
        period: 60 #Timeunit, second
      /v1/template/get:
        capacity: 10 #max number of tokens the bucket can hold 
        tokens: 10 #new tokens add per period
        period: 60 #Timeunit, second
      /v1/template/put:
        capacity: 10 #max number of tokens the bucket can hold 
        tokens: 10 #new tokens add per period
        period: 60 #Timeunit, second
      /v1/template/delete:
       capacity: 10 #max number of tokens the bucket can hold 
       tokens: 10 #new tokens add per period
       period: 60 #Timeunit, second			
allowed:
  origins: localhost:8080
management: #Spring actuator
  endpoints:
    web:
      exposure: # endpoint: /actuator
        # health - App & subsystem health
        # info - App metadata (version, build, commit)
        # metrics - Prometheus or custom metrics
        # mappings - Controller endpoints overview
        # loggers - Dynamic log level adjustment
        # threaddump - Thread dump for debugging
        # heapdump - Heap dump for memory troubleshooting
        # httptrace - Recent HTTP request traces
        # auditevents - Audit logging
        # shutdown - Graceful shutdown
        include: health,info,metrics,prometheus,mappings,loggers,threaddump,heapdump,httptrace,auditevents,shutdown
  endpoint:
    health:
      show-components: always
      show-details: always
  health:
    mail:
      enabled: true
  metrics:
    tags:
      application: spring # Optional: customize metrics tags
  tracing: # OpenTelemetry integration
    sampling:
      probability: 1.0 # Full tracing in dev, lower in prod
alert:
  slack:
    webhook-url:
  support:
    email:
      to: 
      cc: 
      bcc: jleong963@gmail.com
      replyTo: jleong963@gmail.com
fcm:
  credentialsClasspathPath: "security/firebase/firebase-service-account.json"
springdoc:
  api-docs:
    enabled: true
    path: /api-docs #OpenAPI JSON spec endpoint
  swagger-ui:
    enabled: true
    path: /docs #Swagger UI spec endpoint
    operationsSorter: method #API endpoints are ordered consistently (by HTTP method or tag).
    tagsSorter: alpha #API endpoints are ordered consistently (by HTTP method or tag).
    display-request-duration: true #Shows how long each API call takes (helps with perf debugging).
    tryItOutEnabled: true #Lets developers call APIs from the browser directly.
    syntaxHighlight: #Pretty-prints JSON/XML responses.
      activated: true
  group-configs: #Splits OpenAPI docs into groups.
    - group: v1
      paths-to-match: /api/v1/**
    - group: v2
      paths-to-match: /api/v2/**
resilience4j:
  timelimiter: #Must be in async
    configs: #Global Default Configuration
      default:
        timeout-duration: 1s
        cancel-running-future: true
    instances:
      getAsyncTemplate:
        timeout-duration: 1s
        cancel-running-future: true
  circuitbreaker:
    instances:
      sendEmail:
        sliding-window-size: 50 # Look at the last nth calls.
        failure-rate-threshold: 50 # If ≥ nth% fail → stop calling for nth seconds
        wait-duration-in-open-state: 10s # After nth seconds, breaker moves to half-open to test few call. If successful → breaker closes again.
      sendTokenBasedPushNotification:
        sliding-window-size: 50 # Look at the last nth calls.
        failure-rate-threshold: 50 # If ≥ nth% fail → stop calling for nth seconds
        wait-duration-in-open-state: 10s # After nth seconds, breaker moves to half-open to test few call. If successful → breaker closes again. 
  retry:
    instances:
      sendEmail:
        max-attempts: 3
        wait-duration: 2s
      sendTokenBasedPushNotification:
        max-attempts: 3
        wait-duration: 2s
